### ISSUE TITLE
Pagination?

### ISSUE THREAD

**Issue by ChronoWallet** [ntk148v/hugo-cuisine-book#2]
While I love the boxes, any chance the homepage can carry a max limit or pagination so it's not just a run-on of boxes?

**Comment by ntk148v** [comment]
😺 you're right, let me check tho. Thank you!

**Comment by ntk148v** [comment]
![image](https://github.com/ntk148v/hugo-cuisine-book/assets/10803803/0a02848b-5e36-4895-aa29-3210206e7f39)

hugo-cuisine-book supports pagination in main page and tag page. Sorry for taking so long to implement this.
