### ISSUE TITLE
Search Not Working

### ISSUE THREAD

**Issue by ChronoWallet** [ntk148v/hugo-cuisine-book#3]
The search on this theme doesn't work at all. Completely static.

**Comment by ntk148v** [comment]
Hi @sakanventures,in my local environment, the search does work:

![image](https://github.com/ntk148v/hugo-cuisine-book/assets/10803803/99922843-e859-4806-8bae-f4e81c3731ef)

But the search in [Github Page deployment](https://ntk148v.github.io/mammam/) doesn't work properly.

![image](https://github.com/ntk148v/hugo-cuisine-book/assets/10803803/ca73c14f-d9c2-4ee0-a1f7-92d7f89dfe5d)

I'll check then, thanks for reporting.

**Comment by ntk148v** [comment]
Fixed, you can verify in [mammam site](https://ntk148v.github.io/mammam/). Close it for now, feel free to re-open it if you still face this kind of issue.
